/*
 * gfx full graphics set
 * auto-generated by xbmtool.sh
 */
#ifndef GFX_H
#define GFX_H
#include <stdint.h>
#include "xbmlib.h"

/* full frame for key_a.xbm */
extern const uint8_t gfx_key_a[];

/* full frame for key_b.xbm */
extern const uint8_t gfx_key_b[];

/* full frame for key_c.xbm */
extern const uint8_t gfx_key_c[];

/* full frame for key_d.xbm */
extern const uint8_t gfx_key_d[];

/* full frame for key_e.xbm */
extern const uint8_t gfx_key_e[];

/* full frame for key_flat.xbm */
extern const uint8_t gfx_key_flat[];

/* full frame for key_f.xbm */
extern const uint8_t gfx_key_f[];

/* full frame for key_g.xbm */
extern const uint8_t gfx_key_g[];

/* full frame for key_none.xbm */
extern const uint8_t gfx_key_none[];

/* full frame for key_sharp.xbm */
extern const uint8_t gfx_key_sharp[];

/* full frame for menu_key.xbm */
extern const uint8_t gfx_menu_key[];

/* full frame for menu_metre.xbm */
extern const uint8_t gfx_menu_metre[];

/* full frame for menu_mode.xbm */
extern const uint8_t gfx_menu_mode[];

/* full frame for menu_tempo.xbm */
extern const uint8_t gfx_menu_tempo[];

/* full frame for mode_arp_oct.xbm */
extern const uint8_t gfx_mode_arp_oct[];

/* full frame for mode_arp.xbm */
extern const uint8_t gfx_mode_arp[];

/* full frame for mode_chord_arp_oct.xbm */
extern const uint8_t gfx_mode_chord_arp_oct[];

/* full frame for mode_chord_arp.xbm */
extern const uint8_t gfx_mode_chord_arp[];

/* full frame for mode_chord.xbm */
extern const uint8_t gfx_mode_chord[];

/* full frame for tempo_0.xbm */
extern const uint8_t gfx_tempo_0[];

/* full frame for tempo_1.xbm */
extern const uint8_t gfx_tempo_1[];

/* full frame for tempo_2.xbm */
extern const uint8_t gfx_tempo_2[];

/* full frame for tempo_3.xbm */
extern const uint8_t gfx_tempo_3[];

/* full frame for tempo_4.xbm */
extern const uint8_t gfx_tempo_4[];

/* full frame for tempo_5.xbm */
extern const uint8_t gfx_tempo_5[];

/* full frame for tempo_6.xbm */
extern const uint8_t gfx_tempo_6[];

/* full frame for tempo_7.xbm */
extern const uint8_t gfx_tempo_7[];

/* full frame for tempo_8.xbm */
extern const uint8_t gfx_tempo_8[];

/* full frame for tempo_9.xbm */
extern const uint8_t gfx_tempo_9[];

/* full frame for tempo_none.xbm */
extern const uint8_t gfx_tempo_none[];


#endif
