/*
 * 4chord midi - Nokia 3310 LCD Graphics
 *
 * Automatically generated by create_graphics.sh
 *
 */
#ifndef _GRAPHICS_H_
#define _GRAPHICS_H_

extern const unsigned char gfx_key_a[128];
extern const unsigned char gfx_key_b[128];
extern const unsigned char gfx_key_c[128];
extern const unsigned char gfx_key_d[128];
extern const unsigned char gfx_key_e[128];
extern const unsigned char gfx_key_flat[32];
extern const unsigned char gfx_key_f[128];
extern const unsigned char gfx_key_g[128];
extern const unsigned char gfx_key_none[32];
extern const unsigned char gfx_key_sharp[32];
extern const unsigned char gfx_logo[504];
extern const unsigned char gfx_menu_key[84];
extern const unsigned char gfx_menu_metre[84];
extern const unsigned char gfx_menu_mode[84];
extern const unsigned char gfx_menu_tempo[84];
extern const unsigned char gfx_mode_arp_oct[64];
extern const unsigned char gfx_mode_arp[64];
extern const unsigned char gfx_mode_chord_arp_oct[64];
extern const unsigned char gfx_mode_chord_arp[64];
extern const unsigned char gfx_mode_chord[64];
extern const unsigned char gfx_tempo_0[16];
extern const unsigned char gfx_tempo_1[16];
extern const unsigned char gfx_tempo_2[16];
extern const unsigned char gfx_tempo_3[16];
extern const unsigned char gfx_tempo_4[16];
extern const unsigned char gfx_tempo_5[16];
extern const unsigned char gfx_tempo_6[16];
extern const unsigned char gfx_tempo_7[16];
extern const unsigned char gfx_tempo_8[16];
extern const unsigned char gfx_tempo_9[16];
extern const unsigned char gfx_tempo_none[16];

#endif
