/*
 * intro one-shot animation
 * auto-generated by xbmtool.sh
 */
#ifndef INTRO_H
#define INTRO_H
#include <stdint.h>
#include "xbmlib.h"

/* full frame for frame_01.xbm */
extern const uint8_t intro_frame_01[];

/* diff frame for frame_01.xbm -> frame_02.xbm */
extern const struct xbmlib_diff_frame intro_frame_01__frame_02;

/* diff frame for frame_02.xbm -> frame_03.xbm */
extern const struct xbmlib_diff_frame intro_frame_02__frame_03;

/* diff frame for frame_03.xbm -> frame_04.xbm */
extern const struct xbmlib_diff_frame intro_frame_03__frame_04;

/* diff frame for frame_04.xbm -> frame_05.xbm */
extern const struct xbmlib_diff_frame intro_frame_04__frame_05;

/* diff frame for frame_05.xbm -> frame_06.xbm */
extern const struct xbmlib_diff_frame intro_frame_05__frame_06;

/* diff frame for frame_06.xbm -> frame_07.xbm */
extern const struct xbmlib_diff_frame intro_frame_06__frame_07;

/* diff frame for frame_07.xbm -> frame_08.xbm */
extern const struct xbmlib_diff_frame intro_frame_07__frame_08;

/* diff frame for frame_08.xbm -> frame_09.xbm */
extern const struct xbmlib_diff_frame intro_frame_08__frame_09;

/* diff frame for frame_09.xbm -> frame_10.xbm */
extern const struct xbmlib_diff_frame intro_frame_09__frame_10;

/* diff frame for frame_10.xbm -> frame_11.xbm */
extern const struct xbmlib_diff_frame intro_frame_10__frame_11;

/* diff frame for frame_11.xbm -> frame_12.xbm */
extern const struct xbmlib_diff_frame intro_frame_11__frame_12;


/* one-shot animation frame mapping */
extern const struct xbmlib_frame intro_frames[];
/* one-shot animation number of frames */
extern const uint8_t intro_frames_count;

#endif
